### ISSUE TITLE
Why am I getting this error?

### ISSUE THREAD

**Issue by chintito4ever** [nitobuendia/oura-custom-component#16]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:609
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:59:05 AM (3 occurrences)
Last logged: 1:13:16 PM

[547569659040] The system cannot restart because the configuration is not valid: Invalid config for [sensor.template]: expected dictionary for dictionary value @ data['sensors']. Got [OrderedDict([('name', 'Sleep Breath Average Yesterday'), ('unique_id', 'sleep_breath_average_yesterday'), ('unit_of_measurement', 'bpm'), ('state', '{{ states.sensor.sleep_quality.attributes.yesterday.breath_average }}\n'), ('icon', 'mdi:lungs')]), OrderedDict([('name', 'Sleep Temperature Delta Yesterday'), ('unique_id', 'sleep_temperature_delta_yesterday'), ('unit_of_measurement', '°C'), ('device_class', 'temperature'), ('state', '{{ states.sensor.sleep_quality.attributes.yesterday.temperat.... (See ?, line ?).
[547454649584] The system cannot restart because the configuration is not valid: Invalid config for [sensor.oura]: [yesterday] is an invalid option for [sensor.oura]. Check: sensor.oura->yesterday. (See ?, line ?). Invalid config for [sensor.template]: expected dictionary for dictionary value @ data['sensors']. Got [OrderedDict([('name', 'Sleep Breath Average Yesterday'), ('unique_id', 'sleep_breath_average_yesterday'), ('unit_of_measurement', 'bpm'), ('state', '{{ states.sensor.sleep_quality.attributes.yesterday.breath_average }}\n'), ('icon', 'mdi:lungs')]), OrderedDict([('name', 'Sleep Temperature Delta Yesterday'), ('unique_id', 'sleep_temperature_delta_yesterday'), ('unit_of_measurement', '°C'), ('device_class', 'temperature'), ('state', '{{ states.sensor.sleep_quality.attributes.yesterday.temperat.... (See ?, line ?).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 609, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [sensor.template]: expected dictionary for dictionary value @ data['sensors']. Got [OrderedDict([('name', 'Sleep Breath Average Yesterday'), ('unique_id', 'sleep_breath_average_yesterday'), ('unit_of_measurement', 'bpm'), ('state', '{{ states.sensor.sleep_quality.attributes.yesterday.breath_average }}\n'), ('icon', 'mdi:lungs')]), OrderedDict([('name', 'Sleep Temperature Delta Yesterday'), ('unique_id', 'sleep_temperature_delta_yesterday'), ('unit_of_measurement', '°C'), ('device_class', 'temperature'), ('state', '{{ states.sensor.sleep_quality.attributes.yesterday.temperat.... (See ?, line ?).

**Comment by nitobuendia** [comment]
Hi @chintito4ever - thanks for using the component and coming here to ask. That error seems to related to a [Template sensor](https://www.home-assistant.io/integrations/template/) where you're passing fields that are not expected by the template sensor. This repository is only concerned with Oura sensors, not the templated ones. As such, the [Home-Assistant community](https://community.home-assistant.io/) might be a better suited place to ask and get support. This being said, it would help for anyone to troubleshoot if you pasted the configuration you're using.

**Comment by chintito4ever** [comment]
Thank you for your response. I directly copied template codes from your repo. I tried many ways but get same error. I am not a tech savy so doesn't know what else to do. But without template sensors working this integration is kind of worthless to me. I posted on HA Community too, got few suggestions but those also failed.

- platform: template
  sensors:
    - name: "Sleep Breath Average Yesterday"
      unique_id: sleep_breath_average_yesterday
      unit_of_measurement: bpm
      state: >
        {{ states.sensor.sleep_quality.attributes.yesterday.breath_average }}
      icon: "mdi:lungs"
